AllCops:
  Exclude:
    - 'vendor/**/*'
    - 'bundle/**/*'

Documentation:
  Enabled: false
AlignParameters:
  Enabled: true
Encoding:
  Enabled: false
HashSyntax:
  Enabled: true
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
ClassLength:
  Enabled: false
NumericLiterals:
  MinDigits: 10
AbcSize:
  Enabled: false
MultilineOperationIndentation:
  Enabled: false
RedundantFreeze:
  Enabled: false